config/routes.rb
Rails.application.routes.draw do
  root 'tournaments#index'

  resources :tournaments do
    resources :groups, only: [] do
      collection do
        post :generate
      end
    end
    resources :results, only: [] do
      collection do
        post :generate
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :tournament
  belongs_to :first_team, class_name: 'Team', foreign_key: 'first_team_id'
  belongs_to :second_team, class_name: 'Team', foreign_key: 'second_team_id'
  belongs_to :winner, class_name: 'Team', foreign_key: 'winner_id'

  enum stage: {
    group_a: 'Group A',
    group_b: 'Group B',
    quarter_final: 'Quarter final',
    semi_final: 'Semi final',
    final: 'Final'
  }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :tournament
  belongs_to :team

  enum name: { a: 'A', b: 'B' }
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :tournament

  enum stage: {
    group_a: 'Group A',
    group_b: 'Group B',
    quarter_final: 'Quarter final',
    semi_final: 'Semi final',
    final: 'Final'
  }
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :teams
  has_many :groups
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def generate
    group_builder = GroupBuilder.new(params['tournament_id'])
    group_builder.generate_groups

    notice = 'Groups was successfully created.'
    redirect_to tournament_path(params['tournament_id']), notice: notice
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def generate
    result_generator = ResultGenerator.new(params['tournament_id'])
    result_generator.generate(params['stage'])

    notice = 'Results was successfully generated.'
    redirect_to tournament_path(params['tournament_id']), notice: notice
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :destroy]

  def index
    @tournaments = Tournament.all
  end

  def show; end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)

    if @tournament.save && team_params_present?
      save_teams
      redirect_to @tournament, notice: 'Tournament was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @tournament.destroy
    redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.'
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit(:name)
  end

  def team_params_present?
    16.times do |counter|
      return false unless params['tournament']["team#{counter}_name"].present?
    end
    true
  end

  def save_teams
    16.times do |counter|
      @tournament.teams.create(
        name: params['tournament']["team#{counter}_name"]
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TournamentGrid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament, local: true) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Tournament name:' %>
    <%= form.text_field :name %>
  </div>

  <h3>Tournament teams:</h3>

  <% 16.times do |counter| %>
    <div class="field">
      <label for="team<%= counter %>_name">Team <%= counter + 1 %> name:</label>
      <input type="text" name="tournament[team<%= counter %>_name]" id="team<%= counter %>_name">
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/_groups.html.erb
<% if @tournament.groups.present? %>
  <hr>
  <table border="1">
    <tr>
      <th>Group A</th>
      <th>Group B</th>
    </tr>
    <% 8.times do |counter| %>
      <tr>
        <td><%= @tournament.groups.a[counter].team.name %></td>
        <td><%= @tournament.groups.b[counter].team.name %></td>
      </tr>
    <% end %>
  </table>
  <% if @tournament.games.group_a.blank? %>
    <%= link_to 'Generate results for Group A', generate_tournament_results_path(@tournament, stage: 'Group A'), method: :post %>
  <% end %>
  <% if @tournament.games.group_b.blank? %>
    <br>
    <%= link_to 'Generate results for Group B', generate_tournament_results_path(@tournament, stage: 'Group B'), method: :post %>
  <% end %>
  <% if @tournament.games.group_a.present? %>
    <h3>Results (Group A):</h3>
    <table border="1">
      <tr>
        <th>Name</th>
        <th>Wins</th>
      </tr>
      <% @tournament.teams.group_a.order(wins: :desc).each do |team| %>
        <tr>
          <td><%= team.name %></td>
          <td><%= team.wins %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <% if @tournament.games.group_b.present? %>
    <h3>Results (Group B):</h3>
    <table border="1">
      <tr>
        <th>Name</th>
        <th>Wins</th>
      </tr>
      <% @tournament.teams.group_b.order(wins: :desc).each do |team| %>
        <tr>
          <td><%= team.name %></td>
          <td><%= team.wins %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <% if @tournament.games.group_a.present? %>
    <h3>Matches (Group A):</h3>
    <table border="1">
      <tr>
        <th>First team</th>
        <th>Second team</th>
        <th>Winner</th>
      </tr>
      <% @tournament.games.group_a.each do |team| %>
        <tr>
          <td><%= team.first_team.name %></td>
          <td><%= team.second_team.name %></td>
          <td><%= team.winner.name %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <% if @tournament.games.group_b.present? %>
    <h3>Matches (Group B):</h3>
    <table border="1">
      <tr>
        <th>First team</th>
        <th>Second team</th>
        <th>Winner</th>
      </tr>
      <% @tournament.games.group_b.each do |team| %>
        <tr>
          <td><%= team.first_team.name %></td>
          <td><%= team.second_team.name %></td>
          <td><%= team.winner.name %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/tournaments/_play_off.html.erb
<% if @tournament.games.group_a.present? && @tournament.games.group_b.present? %>
  <hr>
  <% if @tournament.games.quarter_final.blank? %>
    <%= link_to 'Generate results Play', generate_tournament_results_path(@tournament, stage: 'Play-off'), method: :post %>
  <% else %>
    <h3>Winner: <%= @tournament.games.final.first.winner.name %></h3>

    <hr>
    <h3>Final game:</h3>
    <table border="1">
      <tr>
        <th>First team:</th>
        <th>Second team:</th>
        <th>Winner:</th>
      </tr>
      <% @tournament.games.final.each do |game| %>
        <tr>
          <td><%= game.first_team.name %></td>
          <td><%= game.second_team.name %></td>
          <td><%= game.winner.name %></td>
        </tr>
      <% end %>
    </table>

    <hr>
    <h3>Semi final games:</h3>
    <table border="1">
      <tr>
        <th>First team:</th>
        <th>Second team:</th>
        <th>Winner:</th>
      </tr>
      <% @tournament.games.semi_final.each do |game| %>
        <tr>
          <td><%= game.first_team.name %></td>
          <td><%= game.second_team.name %></td>
          <td><%= game.winner.name %></td>
        </tr>
      <% end %>
    </table>

    <hr>
    <h3>Quarter final games:</h3>
    <table border="1">
      <tr>
        <th>First team:</th>
        <th>Second team:</th>
        <th>Winner:</th>
      </tr>
      <% @tournament.games.quarter_final.each do |game| %>
        <tr>
          <td><%= game.first_team.name %></td>
          <td><%= game.second_team.name %></td>
          <td><%= game.winner.name %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/tournaments/_teams.html.erb
<% if @tournament.groups.blank? %>
  <hr>
  <%= link_to 'Generate groups', generate_tournament_groups_path(@tournament.id), method: :post %>
<% end %>
<hr>
<h3>All Teams</h3>
<% counter = 1 %>
<% @tournament.teams.each do |team| %>
  <h6>Team <%= counter %> name: <%= team.name %></h6>
  <% counter += 1 %>
<% end %>
<hr>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tournaments</h1>

<% if @tournaments.present? %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  Tournaments have not been created yet
<% end %>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament, teams: @teams %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tournament name:</strong>
  <%= @tournament.name %>
</p>

<%= render partial: 'play_off' %>
<%= render partial: 'groups' %>
<%= render partial: 'teams' %>

<%= link_to 'Back', tournaments_path %>